-- ==============================================================================
-- Supabase Schema for Zowar Taiba (مؤسسة زوار طيبة للنقل البري)
-- Run this script in your Supabase SQL Editor: Dashboard -> SQL Editor -> New query
-- ==============================================================================

-- 1. Create Drivers Table
CREATE TABLE IF NOT EXISTS public.drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_id TEXT UNIQUE NOT NULL,
    driver_name TEXT NOT NULL,
    mobile TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Cars Table
CREATE TABLE IF NOT EXISTS public.cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number TEXT UNIQUE NOT NULL,
    car_model TEXT NOT NULL,
    car_color TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. (Optional) Create Trips / Bookings History Table
CREATE TABLE IF NOT EXISTS public.trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id TEXT NOT NULL,
    trip_date TEXT,
    car_plate TEXT,
    car_model TEXT,
    driver_name TEXT,
    driver_national_id TEXT,
    driver_mobile TEXT,
    guest_name TEXT,
    guest_phone TEXT,
    second_driver TEXT,
    pdf_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 4. Enable Row Level Security (RLS) & Policies
-- ==============================================================================

ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;

-- Allow public / anon / service role to read and manage drivers
CREATE POLICY "Public Read Access - Drivers" 
ON public.drivers FOR SELECT 
USING (true);

CREATE POLICY "Public Manage Access - Drivers" 
ON public.drivers FOR ALL 
USING (true) 
WITH CHECK (true);

-- Allow public / anon / service role to read and manage cars
CREATE POLICY "Public Read Access - Cars" 
ON public.cars FOR SELECT 
USING (true);

CREATE POLICY "Public Manage Access - Cars" 
ON public.cars FOR ALL 
USING (true) 
WITH CHECK (true);

-- Allow public / anon / service role for trips
CREATE POLICY "Public Access - Trips" 
ON public.trips FOR ALL 
USING (true) 
WITH CHECK (true);

-- ==============================================================================
-- 5. Create Storage Bucket for PDFs
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public) 
VALUES ('trip-pdfs', 'trip-pdfs', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policy to allow anyone with the link to view/download PDF documents
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Public Access for trip-pdfs'
    ) THEN
        CREATE POLICY "Public Access for trip-pdfs" 
        ON storage.objects FOR SELECT 
        USING (bucket_id = 'trip-pdfs');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Allow Uploads for trip-pdfs'
    ) THEN
        CREATE POLICY "Allow Uploads for trip-pdfs" 
        ON storage.objects FOR INSERT 
        WITH CHECK (bucket_id = 'trip-pdfs');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Allow Updates for trip-pdfs'
    ) THEN
        CREATE POLICY "Allow Updates for trip-pdfs" 
        ON storage.objects FOR UPDATE 
        USING (bucket_id = 'trip-pdfs');
    END IF;
END $$;

-- ==============================================================================
-- 6. Initial Seed Data (from current drivers.json and cars.json)
-- ==============================================================================

INSERT INTO public.drivers (national_id, driver_name, mobile) VALUES
('2342988280', 'تامر فتحي حسن عليوه', '0534429950'),
('2602571073', 'حسام عبدالصادق محمد الشويل', '+966 53 468 9262'),
('2618944397', 'أحمد ابراهيم السيد الشناوى', '+966 57 301 5001'),
('2567137126', 'محمود جمال بسيونى باشا', '+966 57 457 0840'),
('2474316730', 'عيون صابر صالح رمضان', '+966 54 243 5168')
ON CONFLICT (national_id) DO NOTHING;

INSERT INTO public.cars (plate_number, car_model, car_color) VALUES
('ا ص م 4052', 'تويوتا ميكروباص', 'ابيض'),
('ا ص س 8122', 'تويوتا HIACE', 'ابيض'),
('ا ص س 8138', 'تويوتا HIACE', 'ابيض'),
('ا ص س 8148', 'تويوتا HIACE', 'ابيض'),
('ا ط ل 9425', 'هيونداي STARIA', 'اسود'),
('ا ط ا 7022', 'هيونداي STARIA', 'فضي'),
('ا س و 8258', 'هيونداي STARIA', 'ابيض')
ON CONFLICT (plate_number) DO NOTHING;
